# -*- coding: utf-8 -*-
"""Growth Service — orchestrates the Growth Agent chat flow.

Manages the full agent lifecycle:
    Start -> Chat (QUESTIONING) -> Auto-ANALYZING -> REPORT

Now powered by the PlanningAgent framework:
    - PlanningAgent base class with 8-step workflow
    - Dynamic follow-up questions (LLM-generated, not fixed scripts)
    - Unified JSON output format
    - PlanningRouter for agent registry
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from loguru import logger
from sqlalchemy.orm import Session

from core.exceptions import NotFoundException, AppException
from planning import PlanningAgent, PlanningState, PlanningRouter, WorkflowStep
from models.growth import GrowthSession, GrowthConversation, GrowthReport
from schemas.growth import (
    AgentTypeEnum,
    GrowthChatRequest,
    GrowthStartRequest,
    GrowthChatResponse,
    GrowthStateResponse,
    GrowthHistoryResponse,
    GrowthSessionSummary,
    GrowthReportResponse,
    ConversationMessage,
    QuestionCard,
)
from crud.base import CRUDBase
from crud.user import user as user_crud


session_crud = CRUDBase[GrowthSession](GrowthSession)
conv_crud = CRUDBase[GrowthConversation](GrowthConversation)
report_crud = CRUDBase[GrowthReport](GrowthReport)

MAX_FOLLOW_UP = 7


class GrowthService:
    """Orchestrates Growth Agent conversations using PlanningAgent framework.

    Each turn:
        1. Load or create session
        2. Load or create agent via PlanningRouter
        3. Call agent.chat(message) — dynamic follow-up or analysis
        4. Persist conversation + state to DB
        5. Return response with next question or report
    """

    def __init__(self, llm_service: Any) -> None:
        self.llm = llm_service
        self.router = PlanningRouter(llm_service)
        self._agents: dict[str, PlanningAgent] = {}

    # ── Public API ────────────────────────────────────────────

    def start_session(
        self, db: Session, *, request: GrowthStartRequest
    ) -> GrowthChatResponse:
        """Start a new growth session and return the first question.

        Creates a PlanningAgent, initializes state, and fires the first
        dynamic follow-up question via agent.chat().
        """
        agent_type = (
            request.agent.value
            if isinstance(request.agent, AgentTypeEnum)
            else request.agent
        )

        logger.info(
            "Growth: Starting session for user={}, agent={}",
            request.user_id, agent_type,
        )

        agent = self.router.get_agent(agent_type)

        # Load user profile from registration data
        user = user_crud.get(db, id=request.user_id)
        profile = {}
        if user:
            if user.nickname:
                profile["nickname"] = user.nickname
            if user.major:
                profile["major"] = user.major
            if user.grade:
                profile["grade"] = user.grade

        agent.init_state(user_profile=profile)

        # Kick off the workflow — starts at FOLLOW_UP with profile context
        result = agent.chat("")

        # Create DB session
        session = session_crud.create(db, obj_in={
            "user_id": request.user_id,
            "agent_type": agent_type,
            "status": "active",
            "stage": "questioning",
            "current_step": 0,
            "total_steps": MAX_FOLLOW_UP,
            "state_json": json.dumps(result.get("state", {}), ensure_ascii=False),
            "progress": 0.0,
        })

        self._agents[session.id] = agent

        conv_crud.create(db, obj_in={
            "session_id": session.id,
            "user_id": request.user_id,
            "role": "system",
            "content": "Growth session started: {}".format(agent_type),
            "step": 0,
            "stage": "questioning",
        })

        logger.info("Growth: Session {} started", session.id)

        return self._build_chat_response(session.id, agent_type, agent.agent_label, result)

    def chat(
        self, db: Session, *, request: GrowthChatRequest
    ) -> GrowthChatResponse:
        """Process a chat message and advance the agent flow.

        If session_id is None, auto-creates a new session.
        If session_id is provided, continues an existing session.

        Follow-up questions are dynamically generated by the PlanningAgent's
        LLM-powered question engine — NOT a fixed question list.
        When questioning completes, analysis runs automatically inside
        agent.chat() and returns the unified JSON report.
        """
        agent_type = (
            request.agent.value
            if isinstance(request.agent, AgentTypeEnum)
            else request.agent
        )

        # ── Auto-create session ──
        if request.session_id is None:
            return self.start_session(
                db,
                request=GrowthStartRequest(
                    user_id=request.user_id,
                    agent=request.agent,
                ),
            )

        # ── Resume existing session ──
        session = session_crud.get(db, id=request.session_id)
        if session is None:
            raise NotFoundException("Session {} not found".format(request.session_id))

        agent = self._get_or_restore_agent(db, session)

        # Save user message
        conv_crud.create(db, obj_in={
            "session_id": session.id,
            "user_id": request.user_id,
            "role": "user",
            "content": request.message,
            "step": session.current_step,
            "stage": session.stage,
        })

        # Process through PlanningAgent
        result = agent.chat(request.message)

        # Save agent response
        agent_msg = result.get("message", "")
        if agent_msg:
            conv_crud.create(db, obj_in={
                "session_id": session.id,
                "user_id": request.user_id,
                "role": "assistant",
                "content": agent_msg,
                "step": result.get("follow_up_round", session.current_step),
                "stage": result.get("step", session.stage),
            })

        # Update DB session
        follow_up_round = result.get("follow_up_round", 0)
        finished = result.get("finished", False)
        step_name = result.get("step", "follow_up")
        stage = "report" if finished else "questioning"

        update_data: dict[str, Any] = {
            "stage": stage,
            "current_step": follow_up_round,
            "total_steps": MAX_FOLLOW_UP,
            "state_json": json.dumps(result.get("state", {}), ensure_ascii=False),
            "progress": min(1.0, follow_up_round / MAX_FOLLOW_UP) if not finished else 1.0,
        }
        if finished:
            update_data["status"] = "completed"

        session_crud.update(db, db_obj=session, obj_in=update_data)

        # Persist report if generated
        report = result.get("report")
        if finished and report:
            session.report_json = json.dumps(report, ensure_ascii=False)
            self._save_report(db, session, report)

        # Cache agent
        self._agents[session.id] = agent

        return self._build_chat_response(session.id, agent_type, agent.agent_label, result)

    def get_state(
        self, db: Session, *, user_id: str
    ) -> GrowthStateResponse:
        """Get current growth session state for a user."""
        sessions = session_crud.get_multi(
            db, user_id=user_id, status="active", limit=1
        )
        if not sessions:
            return GrowthStateResponse()

        s = sessions[0]
        state_data = {}
        if s.state_json:
            try:
                state_data = json.loads(s.state_json)
            except json.JSONDecodeError:
                pass

        return GrowthStateResponse(
            session_id=s.id,
            agent=s.agent_type,
            stage=s.stage,
            finished=(s.status == "completed"),
            current_step=s.current_step,
            total_steps=s.total_steps,
            answers=state_data.get("follow_up_answers", {}),
            has_report=bool(s.report_json),
            created_at=s.created_at,
            updated_at=s.updated_at,
        )

    def get_history(
        self, db: Session, *, user_id: str, limit: int = 20
    ) -> GrowthHistoryResponse:
        """Get growth session history for a user."""
        sessions = session_crud.get_multi(
            db, user_id=user_id, limit=limit, order_by="created_at desc"
        )
        summaries = [
            GrowthSessionSummary(
                session_id=s.id,
                agent=s.agent_type,
                status=s.status,
                finished=(s.status == "completed"),
                created_at=s.created_at,
                message_count=len(
                    conv_crud.get_multi(db, session_id=s.id, limit=1000)
                ),
            )
            for s in sessions
        ]
        return GrowthHistoryResponse(user_id=user_id, sessions=summaries)

    def get_report(
        self, db: Session, *, session_id: str
    ) -> GrowthReportResponse:
        """Get the final growth report for a completed session."""
        session = session_crud.get(db, id=session_id)
        if session is None:
            raise NotFoundException("Session {} not found".format(session_id))
        if not session.report_json:
            raise AppException("Report not yet generated for this session.")

        try:
            report = json.loads(session.report_json)
        except json.JSONDecodeError:
            report = {}

        return GrowthReportResponse(
            session_id=session.id,
            agent=session.agent_type,
            report=report,
            created_at=session.updated_at,
        )

    def get_conversation(
        self, db: Session, *, session_id: str
    ) -> list[ConversationMessage]:
        """Get all conversation messages for a session."""
        msgs = conv_crud.get_multi(db, session_id=session_id, limit=200)
        return [ConversationMessage.model_validate(m) for m in msgs]

    # ── Private helpers ───────────────────────────────────────

    def _get_or_restore_agent(
        self, db: Session, session: GrowthSession
    ) -> PlanningAgent:
        """Get cached agent or restore from DB state."""
        if session.id in self._agents:
            logger.debug("Growth: Using cached agent for session {}", session.id)
            return self._agents[session.id]

        agent = self.router.get_agent(session.agent_type)
        if session.state_json:
            try:
                state_data = json.loads(session.state_json)
                state = PlanningState.from_dict(state_data)
                agent.restore_state(state)
            except (json.JSONDecodeError, Exception) as e:
                logger.warning(
                    "Growth: Failed to restore state, reinitializing: {}", e
                )
                agent.init_state()
        else:
            agent.init_state()

        self._agents[session.id] = agent
        logger.debug("Growth: Agent restored for session {}", session.id)
        return agent

    def _build_chat_response(
        self,
        session_id: str,
        agent_type: str,
        agent_label: str,
        result: dict[str, Any],
    ) -> GrowthChatResponse:
        """Map PlanningAgent.chat() result to GrowthChatResponse."""
        step = result.get("step", "follow_up")
        finished = result.get("finished", False)
        follow_up_round = result.get("follow_up_round", 0)
        message = result.get("message", "")

        if finished:
            stage = "report"
            next_question = None
        else:
            stage = "questioning"
            next_question = QuestionCard(
                id="follow_up_{}".format(follow_up_round + 1),
                title=message,
                options=[],
                required=True,
                index=follow_up_round + 1,
                total=MAX_FOLLOW_UP,
            ) if message else None

        return GrowthChatResponse(
            session_id=session_id,
            agent=agent_type,
            stage=stage,
            finished=finished,
            current_step=follow_up_round,
            total_steps=MAX_FOLLOW_UP,
            next_question=next_question,
            report=result.get("report"),
            message=message,
        )

    def _save_report(
        self, db: Session, session: GrowthSession, report: dict[str, Any]
    ) -> None:
        """Save the final report to the GrowthReport table.

        Maps the PlanningAgent unified JSON format to the DB columns.
        """
        existing = report_crud.get_multi(db, session_id=session.id, limit=1)
        report_json_str = json.dumps(report, ensure_ascii=False)

        obj_in = {
            "full_report_json": report_json_str,
            "profile_json": json.dumps(
                {"current_status": report.get("current_status", "")},
                ensure_ascii=False,
            ),
            "analysis_json": json.dumps(
                {
                    "summary": report.get("summary", ""),
                    "main_problem": report.get("main_problem", ""),
                    "goal": report.get("goal", ""),
                },
                ensure_ascii=False,
            ),
            "advantages_json": json.dumps(
                report.get("advantages", []), ensure_ascii=False
            ),
            "risks_json": json.dumps(
                report.get("risks", []), ensure_ascii=False
            ),
            "recommendations_json": json.dumps(
                report.get("action_plan", []), ensure_ascii=False
            ),
            "plan_json": json.dumps(
                report.get("action_plan", []), ensure_ascii=False
            ),
        }

        if existing:
            report_crud.update(db, db_obj=existing[0], obj_in=obj_in)
        else:
            report_crud.create(db, obj_in={
                "session_id": session.id,
                "user_id": session.user_id,
                "agent_type": session.agent_type,
                "report_type": "{}_report".format(session.agent_type),
                **obj_in,
            })

        logger.info("Growth: Report persisted for session {}", session.id)


# ── Singleton ──────────────────────────────────────────────────

_growth_service: GrowthService | None = None


def get_growth_service(llm_service: Any | None = None) -> GrowthService:
    """Return the singleton GrowthService instance."""
    global _growth_service
    if _growth_service is None:
        if llm_service is None:
            from services.llm_service import get_llm_service
            llm_service = get_llm_service()
        _growth_service = GrowthService(llm_service)
    return _growth_service
