# -*- coding: utf-8 -*-
"""Growth Agent API — chat-based conversation flow endpoints.

Endpoints:
  POST /growth/chat      — Send a message, get next question or report
  POST /growth/start     — Start a new growth session
  GET  /growth/state/{user_id}   — Get current session state
  GET  /growth/history/{user_id}  — Get session history
  GET  /growth/report/{session_id} — Get final report
  GET  /growth/agents    — List available agents

Powered by PlanningAgent framework (dynamic follow-up, unified JSON output).
"""

from typing import Any

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from loguru import logger

from database.session import get_db
from schemas.response import APIResponse
from schemas.growth import (
    GrowthChatRequest,
    GrowthStartRequest,
    GrowthChatResponse,
    GrowthStateResponse,
    GrowthHistoryResponse,
    GrowthReportResponse,
    AgentListResponse,
)
from services.growth_service import get_growth_service
from services.llm_service import get_llm_service
from planning.router import PlanningRouter

router = APIRouter(prefix="/growth", tags=["growth"])


@router.post("/chat", response_model=APIResponse[GrowthChatResponse])
async def growth_chat(
    request: GrowthChatRequest,
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Send a message to a growth agent.

    If session_id is provided, continues an existing session.
    If session_id is None, auto-creates a new session.

    Questions are dynamically generated by the PlanningAgent — not a fixed script.
    When enough information is collected, the agent automatically analyzes and
    returns a structured JSON report.
    """
    logger.info("POST /growth/chat user={}, agent={}", request.user_id, request.agent)
    llm = get_llm_service()
    service = get_growth_service(llm)
    result = service.chat(db, request=request)
    return APIResponse.ok(data=result).model_dump()


@router.post("/start", response_model=APIResponse[GrowthChatResponse])
async def growth_start(
    request: GrowthStartRequest,
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Start a new growth session.

    Creates a PlanningAgent instance, initializes the 8-step workflow,
    and returns the first dynamic follow-up question.
    """
    logger.info("POST /growth/start user={}, agent={}", request.user_id, request.agent)
    llm = get_llm_service()
    service = get_growth_service(llm)
    result = service.start_session(db, request=request)
    return APIResponse.ok(data=result).model_dump()


@router.get("/state/{user_id}", response_model=APIResponse[GrowthStateResponse])
async def growth_state(
    user_id: str,
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Get the current growth session state for a user."""
    logger.debug("GET /growth/state user={}", user_id)
    llm = get_llm_service()
    service = get_growth_service(llm)
    result = service.get_state(db, user_id=user_id)
    return APIResponse.ok(data=result).model_dump()


@router.get("/history/{user_id}", response_model=APIResponse[GrowthHistoryResponse])
async def growth_history(
    user_id: str,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Get growth session history for a user."""
    logger.debug("GET /growth/history user={}, limit={}", user_id, limit)
    llm = get_llm_service()
    service = get_growth_service(llm)
    result = service.get_history(db, user_id=user_id, limit=limit)
    return APIResponse.ok(data=result).model_dump()


@router.get("/report/{session_id}", response_model=APIResponse[GrowthReportResponse])
async def growth_report(
    session_id: str,
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Get the final growth report for a completed session."""
    logger.debug("GET /growth/report session={}", session_id)
    llm = get_llm_service()
    service = get_growth_service(llm)
    result = service.get_report(db, session_id=session_id)
    return APIResponse.ok(data=result).model_dump()


@router.get("/agents", response_model=APIResponse[AgentListResponse])
async def list_agents() -> dict[str, Any]:
    """List all available growth agents (career, graduate, civil, major)."""
    agents = PlanningRouter.list_agents()
    return APIResponse.ok(data={"agents": agents}).model_dump()
