# -*- coding: utf-8 -*-
"""Planning Agent Prompts — 方案 B: 全部 4 个 Agent 已拆分."""

from planning.prompts.career import (
    CAREER_ANALYZE_PROMPT,
    CAREER_GOAL_PROMPT,
    CAREER_TASK_FILL_PROMPT,
    CAREER_ANALYSIS_STRATEGY,
    CAREER_PLANNING_PROMPT,
)
from planning.prompts.graduate import (
    GRADUATE_ANALYZE_PROMPT,
    GRADUATE_GOAL_PROMPT,
    GRADUATE_TASK_FILL_PROMPT,
    GRADUATE_ANALYSIS_STRATEGY,
    GRADUATE_PLANNING_PROMPT,
)
from planning.prompts.civil import (
    CIVIL_ANALYZE_PROMPT,
    CIVIL_GOAL_PROMPT,
    CIVIL_TASK_FILL_PROMPT,
    CIVIL_ANALYSIS_STRATEGY,
    CIVIL_PLANNING_PROMPT,
)
from planning.prompts.major import (
    MAJOR_ANALYZE_PROMPT,
    MAJOR_GOAL_PROMPT,
    MAJOR_TASK_FILL_PROMPT,
    MAJOR_ANALYSIS_STRATEGY,
    MAJOR_PLANNING_PROMPT,
)

__all__ = [
    "CAREER_ANALYZE_PROMPT", "CAREER_GOAL_PROMPT", "CAREER_TASK_FILL_PROMPT",
    "CAREER_PLANNING_PROMPT", "CAREER_ANALYSIS_STRATEGY",
    "GRADUATE_ANALYZE_PROMPT", "GRADUATE_GOAL_PROMPT", "GRADUATE_TASK_FILL_PROMPT",
    "GRADUATE_PLANNING_PROMPT", "GRADUATE_ANALYSIS_STRATEGY",
    "CIVIL_ANALYZE_PROMPT", "CIVIL_GOAL_PROMPT", "CIVIL_TASK_FILL_PROMPT",
    "CIVIL_PLANNING_PROMPT", "CIVIL_ANALYSIS_STRATEGY",
    "MAJOR_ANALYZE_PROMPT", "MAJOR_GOAL_PROMPT", "MAJOR_TASK_FILL_PROMPT",
    "MAJOR_PLANNING_PROMPT", "MAJOR_ANALYSIS_STRATEGY",
]
